<?php

namespace Proxies\__CG__\MProd\LicenciaCyPBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Persona extends \MProd\LicenciaCyPBundle\Entity\Persona implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\Persona' . "\0" . 'id', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\Persona' . "\0" . 'nombre', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\Persona' . "\0" . 'apellido', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\Persona' . "\0" . 'fechaNacimiento', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\Persona' . "\0" . 'domicilioCalle', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\Persona' . "\0" . 'domicilioNumero', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\Persona' . "\0" . 'localidad', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\Persona' . "\0" . 'localidadOtraProvincia', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\Persona' . "\0" . 'tipoDocumento', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\Persona' . "\0" . 'numeroDocumento', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\Persona' . "\0" . 'sexo', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\Persona' . "\0" . 'jubilado', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\Persona' . "\0" . 'telefono', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\Persona' . "\0" . 'email', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\Persona' . "\0" . 'provincia', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\Persona' . "\0" . 'licencias', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\Persona' . "\0" . 'createdAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\Persona' . "\0" . 'id', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\Persona' . "\0" . 'nombre', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\Persona' . "\0" . 'apellido', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\Persona' . "\0" . 'fechaNacimiento', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\Persona' . "\0" . 'domicilioCalle', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\Persona' . "\0" . 'domicilioNumero', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\Persona' . "\0" . 'localidad', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\Persona' . "\0" . 'localidadOtraProvincia', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\Persona' . "\0" . 'tipoDocumento', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\Persona' . "\0" . 'numeroDocumento', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\Persona' . "\0" . 'sexo', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\Persona' . "\0" . 'jubilado', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\Persona' . "\0" . 'telefono', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\Persona' . "\0" . 'email', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\Persona' . "\0" . 'provincia', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\Persona' . "\0" . 'licencias', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\Persona' . "\0" . 'createdAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Persona $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getProvincia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProvincia', []);

        return parent::getProvincia();
    }

    /**
     * {@inheritDoc}
     */
    public function setProvincia(\MProd\LicenciaCyPBundle\Entity\Provincia $provincia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProvincia', [$provincia]);

        return parent::setProvincia($provincia);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellido', []);

        return parent::getApellido();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellido($apellido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellido', [$apellido]);

        return parent::setApellido($apellido);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaNacimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaNacimiento', []);

        return parent::getFechaNacimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaNacimiento($fechaNacimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaNacimiento', [$fechaNacimiento]);

        return parent::setFechaNacimiento($fechaNacimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalidad', []);

        return parent::getLocalidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalidad($localidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalidad', [$localidad]);

        return parent::setLocalidad($localidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalidadOtraProvincia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalidadOtraProvincia', []);

        return parent::getLocalidadOtraProvincia();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalidadOtraProvincia($localidadOtraProvincia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalidadOtraProvincia', [$localidadOtraProvincia]);

        return parent::setLocalidadOtraProvincia($localidadOtraProvincia);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroDocumento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroDocumento', []);

        return parent::getNumeroDocumento();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroDocumento($numeroDocumento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroDocumento', [$numeroDocumento]);

        return parent::setNumeroDocumento($numeroDocumento);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexo', []);

        return parent::getSexo();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexo($sexo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexo', [$sexo]);

        return parent::setSexo($sexo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', []);

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', [$telefono]);

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoDocumento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoDocumento', []);

        return parent::getTipoDocumento();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoDocumento($tipoDocumento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoDocumento', [$tipoDocumento]);

        return parent::setTipoDocumento($tipoDocumento);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAtValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAtValue', []);

        return parent::setCreatedAtValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function addLicencia(\MProd\LicenciaCyPBundle\Entity\Licencia $licencias)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLicencia', [$licencias]);

        return parent::addLicencia($licencias);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLicencia(\MProd\LicenciaCyPBundle\Entity\Licencia $licencias)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLicencia', [$licencias]);

        return parent::removeLicencia($licencias);
    }

    /**
     * {@inheritDoc}
     */
    public function getLicencias()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLicencias', []);

        return parent::getLicencias();
    }

    /**
     * {@inheritDoc}
     */
    public function setJubilado($jubilado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJubilado', [$jubilado]);

        return parent::setJubilado($jubilado);
    }

    /**
     * {@inheritDoc}
     */
    public function getJubilado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJubilado', []);

        return parent::getJubilado();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomicilioCalle($domicilioCalle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomicilioCalle', [$domicilioCalle]);

        return parent::setDomicilioCalle($domicilioCalle);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomicilioCalle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomicilioCalle', []);

        return parent::getDomicilioCalle();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomicilioNumero($domicilioNumero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomicilioNumero', [$domicilioNumero]);

        return parent::setDomicilioNumero($domicilioNumero);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomicilioNumero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomicilioNumero', []);

        return parent::getDomicilioNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function copyValues($objectForCopy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'copyValues', [$objectForCopy]);

        return parent::copyValues($objectForCopy);
    }

}
