<?php

namespace Proxies\__CG__\MProd\LicenciaCyPBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TipoLicencia extends \MProd\LicenciaCyPBundle\Entity\TipoLicencia implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\TipoLicencia' . "\0" . 'id', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\TipoLicencia' . "\0" . 'descripcion', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\TipoLicencia' . "\0" . 'generoJubilado', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\TipoLicencia' . "\0" . 'clienteSap', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\TipoLicencia' . "\0" . 'letraServicio', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\TipoLicencia' . "\0" . 'arancel', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\TipoLicencia' . "\0" . 'porcentajeRecargoPrimerVencimiento', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\TipoLicencia' . "\0" . 'porcentajeRecargoSegundoVencimiento', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\TipoLicencia' . "\0" . 'diasVigencia', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\TipoLicencia' . "\0" . 'diasPrimerVencimiento', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\TipoLicencia' . "\0" . 'diasSegundoVencimiento', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\TipoLicencia' . "\0" . 'fechaTope', 'isActive', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\TipoLicencia' . "\0" . 'aplicaEnProvincia'];
        }

        return ['__isInitialized__', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\TipoLicencia' . "\0" . 'id', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\TipoLicencia' . "\0" . 'descripcion', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\TipoLicencia' . "\0" . 'generoJubilado', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\TipoLicencia' . "\0" . 'clienteSap', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\TipoLicencia' . "\0" . 'letraServicio', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\TipoLicencia' . "\0" . 'arancel', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\TipoLicencia' . "\0" . 'porcentajeRecargoPrimerVencimiento', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\TipoLicencia' . "\0" . 'porcentajeRecargoSegundoVencimiento', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\TipoLicencia' . "\0" . 'diasVigencia', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\TipoLicencia' . "\0" . 'diasPrimerVencimiento', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\TipoLicencia' . "\0" . 'diasSegundoVencimiento', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\TipoLicencia' . "\0" . 'fechaTope', 'isActive', '' . "\0" . 'MProd\\LicenciaCyPBundle\\Entity\\TipoLicencia' . "\0" . 'aplicaEnProvincia'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TipoLicencia $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', []);

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', [$descripcion]);

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getArancel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArancel', []);

        return parent::getArancel();
    }

    /**
     * {@inheritDoc}
     */
    public function setArancel($arancel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArancel', [$arancel]);

        return parent::setArancel($arancel);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiasVigencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiasVigencia', []);

        return parent::getDiasVigencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiasVigencia($diasVigencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiasVigencia', [$diasVigencia]);

        return parent::setDiasVigencia($diasVigencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaTope()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaTope', []);

        return parent::getFechaTope();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaTope($fechaTope)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaTope', [$fechaTope]);

        return parent::setFechaTope($fechaTope);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsActive', []);

        return parent::getIsActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsActive($isActive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsActive', [$isActive]);

        return parent::setIsActive($isActive);
    }

    /**
     * {@inheritDoc}
     */
    public function setClienteSap($clienteSap)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClienteSap', [$clienteSap]);

        return parent::setClienteSap($clienteSap);
    }

    /**
     * {@inheritDoc}
     */
    public function getClienteSap()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClienteSap', []);

        return parent::getClienteSap();
    }

    /**
     * {@inheritDoc}
     */
    public function setLetraServicio($letraServicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLetraServicio', [$letraServicio]);

        return parent::setLetraServicio($letraServicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getLetraServicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLetraServicio', []);

        return parent::getLetraServicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiasPrimerVencimiento($diasPrimerVencimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiasPrimerVencimiento', [$diasPrimerVencimiento]);

        return parent::setDiasPrimerVencimiento($diasPrimerVencimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiasPrimerVencimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiasPrimerVencimiento', []);

        return parent::getDiasPrimerVencimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiasSegundoVencimiento($diasSegundoVencimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiasSegundoVencimiento', [$diasSegundoVencimiento]);

        return parent::setDiasSegundoVencimiento($diasSegundoVencimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiasSegundoVencimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiasSegundoVencimiento', []);

        return parent::getDiasSegundoVencimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setPorcentajeRecargoPrimerVencimiento($porcentajeRecargoPrimerVencimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPorcentajeRecargoPrimerVencimiento', [$porcentajeRecargoPrimerVencimiento]);

        return parent::setPorcentajeRecargoPrimerVencimiento($porcentajeRecargoPrimerVencimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getPorcentajeRecargoPrimerVencimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPorcentajeRecargoPrimerVencimiento', []);

        return parent::getPorcentajeRecargoPrimerVencimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setPorcentajeRecargoSegundoVencimiento($porcentajeRecargoSegundoVencimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPorcentajeRecargoSegundoVencimiento', [$porcentajeRecargoSegundoVencimiento]);

        return parent::setPorcentajeRecargoSegundoVencimiento($porcentajeRecargoSegundoVencimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getPorcentajeRecargoSegundoVencimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPorcentajeRecargoSegundoVencimiento', []);

        return parent::getPorcentajeRecargoSegundoVencimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function copyValues($objectForCopy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'copyValues', [$objectForCopy]);

        return parent::copyValues($objectForCopy);
    }

    /**
     * {@inheritDoc}
     */
    public function setGeneroJubilado($generoJubilado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGeneroJubilado', [$generoJubilado]);

        return parent::setGeneroJubilado($generoJubilado);
    }

    /**
     * {@inheritDoc}
     */
    public function getGeneroJubilado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGeneroJubilado', []);

        return parent::getGeneroJubilado();
    }

    /**
     * {@inheritDoc}
     */
    public function setAplicaEnProvincia($aplicaEnProvincia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAplicaEnProvincia', [$aplicaEnProvincia]);

        return parent::setAplicaEnProvincia($aplicaEnProvincia);
    }

    /**
     * {@inheritDoc}
     */
    public function getAplicaEnProvincia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAplicaEnProvincia', []);

        return parent::getAplicaEnProvincia();
    }

}
