imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: "es_AR.UTF-8"

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
 #   form_themes:
 #       - "MProdEmprendedoresBundle:Form:Mensajes_error.html.twig"
    

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    #bundles:        [ MProdEmprendedoresBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
            enum: string
            set: string
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration para envio de emails
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
    
#Configurador del bundle del paginador
knp_paginator:
    page_range: 5  
    default_options:
        page_name: page 
        sort_field_name: sort 
        sort_direction_name: direction 
        distinct: true
    template:
        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig 
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig 

#Configuración del bundle de interfás gráfica para la stg. 
theme_aplicativo:
    datos_aplicativo:
        encabezado:
            titulo: 'Gestión de Licencia Caza y Pesca'
            nombre_dependencia:  'Secretaría de Ganadería, Lechería y Recursos Naturales'
            nombre_organismo: 'Ministerio de la Producción'
            #imagen_top_url:  '../../src/MProd/EmprendedoresBundle/Resources/images/logoCrear1.jpg'
            #path_ayuda: m_prod_emprendedores_ayuda
            path_logout :  logout
            #path_login:   login
            path_home: path_home
            webmaster_correo: agespinosa@santafe.gov.ar
        pie_pagina:
            titulo: 
            domicilio: 
            telefono: 
            copyright:

#Configuración del bundle cas basado en rizeway para la stg. Esto no se va a usar por el momento
#cas:
#        # desarrollo/testing
#        url: https://dsso.santafe.gov.ar/service-auth
#        server: https://dsso.santafe.gov.ar/service-auth # (only if different from the url, for server to server requests)
#        cert: false # false to bypass (opcional)
#        username_attribute: user  # (opcional)
#        proxy: false # if you want to active the proxy cas mode (opcional)                
