m_prod_licencia_cy_p_rendicion:
    resource: "@MProdLicenciaCyPBundle/Controller/RendicionController.php"
    type:     annotation

m_prod_licencia_cy_p:
    resource: "@MProdLicenciaCyPBundle/Resources/config/routing.yml"
    prefix:   /

#Enrutado del bundle de la interfaz gráfica
theme_aplicativo:
    resource: "@ThemeAplicativoBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /