security:

    firewalls:
        page:
            pattern:    ^/*
            anonymous:  ~
            form_login:
                login_path: login
                check_path: login_check
            remember_me:
                key:        licencia1234
                lifetime:   3600
            logout:
                path:   logout
                target: login

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }


    providers:
        usuarios:
            entity: { class: MProd\LicenciaCyPBundle\Entity\Usuario, property: email}

    encoders:
        MProd\LicenciaCyPBundle\Entity\Usuario:
            algorithm: bcrypt
            cost: 12
