services:
    licencia_service:
        class: MProd\LicenciaCyPBundle\Service\LicenciaServiceImpl
        autowire: true

    persona_service:
        class: MProd\LicenciaCyPBundle\Service\PersonaServiceImpl
        autowire: true
    
    tipo_licencia_service:
        class: MProd\LicenciaCyPBundle\Service\TipoLicenciaServiceImpl
        autowire: true
