services:
   
    licencia_service:
        class: MProd\LicenciaCyPBundle\Service\LicenciaServiceImpl
        autowire: true

    persona_service:
        class: MProd\LicenciaCyPBundle\Service\PersonaServiceImpl
        autowire: true
    
    tipo_licencia_service:
        class: MProd\LicenciaCyPBundle\Service\TipoLicenciaServiceImpl
        autowire: true

    json_service:
        class: MProd\LicenciaCyPBundle\Service\JsonServiceImpl
        autowire: true
    
    comprobante_service:
        class: MProd\LicenciaCyPBundle\Service\ComprobanteServiceImpl
        autowire: true

    boleta_service:
        class: MProd\LicenciaCyPBundle\Service\BoletaServiceImpl
        autowire: true

    persona_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - MProd\LicenciaCyPBundle\Entity\Persona        
        autowiring_types: MProd\LicenciaCyPBundle\Repository\IPersonaRepository

    licencia_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - MProd\LicenciaCyPBundle\Entity\Licencia
        autowiring_types: MProd\LicenciaCyPBundle\Repository\ILicenciaRepository
    
    tipo_licencia_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - MProd\LicenciaCyPBundle\Entity\TipoLicencia
        autowiring_types: MProd\LicenciaCyPBundle\Repository\ITipoLicenciaRepository
    
    comprobante_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - MProd\LicenciaCyPBundle\Entity\Comprobante
        autowiring_types: MProd\LicenciaCyPBundle\Repository\IComprobanteRepository