#-------------------------Conexion a db--------------------
# Este archivo sirve para configurar la conexion a la base de datos
#----------------------------------------------------------
# Nota: Respetar la notacion yml : http://yaml.org/
#----------------------------------------------------------
parameters:
    database_host: srvtmysql3e.santafe.gov.ar
    database_port: 3306
    database_name: mprod_emprendedor
    database_user: mprod_uemprend 
    database_password: empre6563
    mailer_transport: smtp
    mailer_encryption: ssl
    mailer_auth_mode: login
    mailer_host: smtp.santafe.gov.ar
    mailer_user: rrecalde
    mailer_password: 
    secret: ThisTokenIsNotSoSecretChangeIt
